# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

image: "python:3.8"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CACHE_COMPRESSION_LEVEL: "fastest"

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cache/pip
    - venv/
  policy: pull

before_script:
  - python -v               # Print out python version for debugging
  - python -m venv venv
  - source venv/bin/activate

stages:
  - iou
  - hungarian_matching
  - recursive_matching
  - krippendorff_calculation
  - fruits_test_case
  - landscape_test_case

iou_pytest:
  stage: iou
  script:
    - python setup.py develop
    - pytest tests/test_iou.py
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/pip
      - venv/
    policy: push

hungarian_matching_pytest:
  stage: hungarian_matching
  script:
  - pytest tests/test_hungarian_matching.py

krippendorff_calculation_pytest:
  stage: krippendorff_calculation
  allow_failure: true
  script:
  - pytest tests/test_krippendorff.py
  -
fruits_testcase_pytest:
  stage: fruits_test_case
  allow_failure: true
  script:
  - pytest tests/test_example_fruits.py

landscape_testcase_pytest:
  stage: landscape_test_case
  allow_failure: true
  script:
  - pytest tests/test_example_landscape.py